### ISSUE TITLE
eip

### ISSUE THREAD

**Issue by ChrisLinn** [HAOYUatHZ/fair-atomic-swap#43]
an eip on fair atomic swap

**Comment by ChrisLinn** [comment]
@SebastianElvis  I plan to finish reading template and have a basic framework by tonight.

And for BIP, I have close the PR. Maybe we should also reply ZmnSCPxj, to explain that we get him wrong in case he get confused?

**Comment by SebastianElvis** [comment]
I think we should reply him an email... For this email, we should do a much more comprehensive one, including his protocol in detail, how he justifies the security, and how we break this protocol.
I will do this later in the noon, and will keep you updated.

**Comment by HAOYUatHZ** [comment]
> I think we should reply him an email... For this email, we should do a much more comprehensive one, including his protocol in detail, how he justifies the security, and how we break this protocol.
> I will do this later in the noon, and will keep you updated.

thx~

**Comment by HAOYUatHZ** [comment]
+ [ ] Define interfaces
    + https://solidity.readthedocs.io/en/v0.5.3/contracts.html#interfaces
    + https://github.com/ethereum/EIPs/blob/master/EIPS/eip-875.md
+ [ ] Define events
    + https://github.com/ethereum/EIPs/blob/master/EIPS/eip-823.md
